<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShuftiProJusrisdictionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jurisdictions = [
            ["id" => 1, "name" => "Abu Dhabi (UAE)", "code" => "ae_az"],
            ["id" => 2, "name" => "Alabama (US)", "code" => "us_al"],
            ["id" => 3, "name" => "Alaska (US)", "code" => "us_ak"],
            ["id" => 4, "name" => "Albania", "code" => "al"],
            ["id" => 5, "name" => "Arizona (US)", "code" => "us_az"],
            ["id" => 6, "name" => "Arkansas (US)", "code" => "us_ar"],
            ["id" => 7, "name" => "Aruba", "code" => "aw"],
            ["id" => 8, "name" => "Australia", "code" => "au"],
            ["id" => 9, "name" => "Bahamas", "code" => "bs"],
            ["id" => 10, "name" => "Bahrain", "code" => "bh"],
            ["id" => 11, "name" => "Bangladesh", "code" => "bd"],
            ["id" => 12, "name" => "Barbados", "code" => "bb"],
            ["id" => 13, "name" => "Belarus", "code" => "by"],
            ["id" => 14, "name" => "Belgium", "code" => "be"],
            ["id" => 15, "name" => "Belize", "code" => "bz"],
            ["id" => 16, "name" => "Bermuda", "code" => "bm"],
            ["id" => 17, "name" => "Bolivia", "code" => "bo"],
            ["id" => 18, "name" => "Brazil", "code" => "br"],
            ["id" => 19, "name" => "Bulgaria", "code" => "bg"],
            ["id" => 20, "name" => "California (US)", "code" => "us_ca"],
            ["id" => 21, "name" => "Cambodia", "code" => "kh"],
            ["id" => 22, "name" => "Canada", "code" => "ca"],
            ["id" => 23, "name" => "Colorado (US)", "code" => "us_co"],
            ["id" => 24, "name" => "Connecticut (US)", "code" => "us_ct"],
            ["id" => 25, "name" => "Croatia", "code" => "hr"],
            ["id" => 26, "name" => "Curaçao", "code" => "cw"],
            ["id" => 27, "name" => "Cyprus", "code" => "cy"],
            ["id" => 28, "name" => "Delaware (US)", "code" => "us_de"],
            ["id" => 29, "name" => "Denmark", "code" => "dk"],
            ["id" => 30, "name" => "District of Columbia (US)", "code" => "us_dc"],
            ["id" => 31, "name" => "Dominican Republic", "code" => "do"],
            ["id" => 32, "name" => "Dubai (UAE)", "code" => "ae_du"],
            ["id" => 33, "name" => "Finland", "code" => "fi"],
            ["id" => 34, "name" => "Florida (US)", "code" => "us_fl"],
            ["id" => 35, "name" => "France", "code" => "fr"],
            ["id" => 36, "name" => "French Guiana", "code" => "gf"],
            ["id" => 37, "name" => "Georgia (US)", "code" => "us_ga"],
            ["id" => 38, "name" => "Germany", "code" => "de"],
            ["id" => 39, "name" => "Gibraltar", "code" => "gi"],
            ["id" => 40, "name" => "Greece", "code" => "gr"],
            ["id" => 41, "name" => "Greenland", "code" => "gl"],
            ["id" => 42, "name" => "Guadeloupe", "code" => "gp"],
            ["id" => 43, "name" => "Guernsey", "code" => "gg"],
            ["id" => 44, "name" => "Hawaii (US)", "code" => "us_hi"],
            ["id" => 45, "name" => "Hong Kong", "code" => "hk"],
            ["id" => 46, "name" => "Iceland", "code" => "is"],
            ["id" => 47, "name" => "Idaho (US)", "code" => "us_id"],
            ["id" => 48, "name" => "India", "code" => "in"],
            ["id" => 49, "name" => "Indiana (US)", "code" => "us_in"],
            ["id" => 50, "name" => "Iowa (US)", "code" => "us_ia"],
            ["id" => 51, "name" => "Iran", "code" => "ir"],
            ["id" => 52, "name" => "Ireland", "code" => "ie"],
            ["id" => 53, "name" => "Isle of Man", "code" => "im"],
            ["id" => 54, "name" => "Israel", "code" => "il"],
            ["id" => 55, "name" => "Jamaica", "code" => "jm"],
            ["id" => 56, "name" => "Japan", "code" => "jp"],
            ["id" => 57, "name" => "Jersey", "code" => "je"],
            ["id" => 58, "name" => "Kansas (US)", "code" => "us_ks"],
            ["id" => 59, "name" => "Kentucky (US)", "code" => "us_ky"],
            ["id" => 60, "name" => "Latvia", "code" => "lv"],
            ["id" => 61, "name" => "Liechtenstein", "code" => "li"],
            ["id" => 62, "name" => "Louisiana (US)", "code" => "us_la"],
            ["id" => 63, "name" => "Luxembourg", "code" => "lu"],
            ["id" => 64, "name" => "Maine (US)", "code" => "us_me"],
            ["id" => 65, "name" => "Malaysia", "code" => "my"],
            ["id" => 66, "name" => "Malta", "code" => "mt"],
            ["id" => 67, "name" => "Martinique", "code" => "mq"],
            ["id" => 68, "name" => "Maryland (US)", "code" => "us_md"],
            ["id" => 69, "name" => "Massachusetts (US)", "code" => "us_ma"],
            ["id" => 70, "name" => "Mauritius", "code" => "mu"],
            ["id" => 71, "name" => "Mayotte", "code" => "yt"],
            ["id" => 72, "name" => "Mexico", "code" => "mx"],
            ["id" => 73, "name" => "Michigan (US)", "code" => "us_mi"],
            ["id" => 74, "name" => "Minnesota (US)", "code" => "us_mn"],
            ["id" => 75, "name" => "Mississippi (US)", "code" => "us_ms"],
            ["id" => 76, "name" => "Missouri (US)", "code" => "us_mo"],
            ["id" => 77, "name" => "Moldova", "code" => "md"],
            ["id" => 78, "name" => "Montana (US)", "code" => "us_mt"],
            ["id" => 79, "name" => "Montenegro", "code" => "me"],
            ["id" => 80, "name" => "Myanmar", "code" => "mm"],
            ["id" => 81, "name" => "Nebraska (US)", "code" => "us_ne"],
            ["id" => 82, "name" => "Netherlands", "code" => "nl"],
            ["id" => 83, "name" => "Nevada (US)", "code" => "us_nv"],
            ["id" => 84, "name" => "New Brunswick (Canada)", "code" => "ca_nb"],
            ["id" => 85, "name" => "New Hampshire (US)", "code" => "us_nh"],
            ["id" => 86, "name" => "New Jersey (US)", "code" => "us_nj"],
            ["id" => 87, "name" => "New Mexico (US)", "code" => "us_nm"],
            ["id" => 88, "name" => "New York (US)", "code" => "us_ny"],
            ["id" => 89, "name" => "New Zealand", "code" => "nz"],
            ["id" => 90, "name" => "Newfoundland and Labrador (Canada)", "code" => "ca_nl"],
            ["id" => 91, "name" => "North Carolina (US)", "code" => "us_nc"],
            ["id" => 92, "name" => "North Dakota", "code" => "us_nd"],
            ["id" => 93, "name" => "Norway", "code" => "no"],
            ["id" => 94, "name" => "Nova Scotia (Canada)", "code" => "ca_ns"],
            ["id" => 95, "name" => "Ohio (US)", "code" => "us_oh"],
            ["id" => 96, "name" => "Oklahoma (US)", "code" => "us_ok"],
            ["id" => 97, "name" => "Ontario (Canada)", "code" => "ca_on"],
            ["id" => 98, "name" => "Oregon (US)", "code" => "us_or"],
            ["id" => 99, "name" => "Pennsylvania (US)", "code" => "us_pa"],
            ["id" => 100, "name" => "Philippines", "code" => "ph"],
            ["id" => 101, "name" => "Poland", "code" => "pl"],
            ["id" => 102, "name" => "Portugal", "code" => "pt"],
            ["id" => 103, "name" => "Qatar", "code" => "qa"],
            ["id" => 104, "name" => "Rhode Island (US)", "code" => "us_ri"],
            ["id" => 105, "name" => "Saint Helena", "code" => "sh"],
            ["id" => 106, "name" => "Saint Kitts and Nevis", "code" => "kn"],
            ["id" => 107, "name" => "Saint Lucia", "code" => "lc"],
            ["id" => 108, "name" => "Saint Martin", "code" => "mf"],
            ["id" => 109, "name" => "Saint Pierre and Miquelon", "code" => "pm"],
            ["id" => 110, "name" => "Saint Vincent and the Grenadines", "code" => "vc"],
            ["id" => 111, "name" => "Samoa", "code" => "ws"],
            ["id" => 112, "name" => "Sao Tome and Principe", "code" => "st"],
            ["id" => 113, "name" => "Saudi Arabia", "code" => "sa"],
            ["id" => 114, "name" => "Scotland", "code" => "gb-sct"],
            ["id" => 115, "name" => "Singapore", "code" => "sg"],
            ["id" => 116, "name" => "Slovakia", "code" => "sk"],
            ["id" => 117, "name" => "Slovenia", "code" => "si"],
            ["id" => 118, "name" => "South Africa", "code" => "za"],
            ["id" => 119, "name" => "South Korea", "code" => "kr"],
            ["id" => 120, "name" => "Spain", "code" => "es"],
            ["id" => 121, "name" => "Sweden", "code" => "se"],
            ["id" => 122, "name" => "Switzerland", "code" => "ch"],
            ["id" => 123, "name" => "Taiwan", "code" => "tw"],
            ["id" => 124, "name" => "Tennessee (US)", "code" => "us_tn"],
            ["id" => 125, "name" => "Texas (US)", "code" => "us_tx"],
            ["id" => 126, "name" => "Thailand", "code" => "th"],
            ["id" => 127, "name" => "Tonga", "code" => "to"],
            ["id" => 128, "name" => "Trinidad and Tobago", "code" => "tt"],
            ["id" => 129, "name" => "Turkey", "code" => "tr"],
            ["id" => 130, "name" => "United Arab Emirates", "code" => "ae"],
            ["id" => 131, "name" => "United Kingdom", "code" => "gb"],
            ["id" => 132, "name" => "United States", "code" => "us"],
            ["id" => 133, "name" => "Uruguay", "code" => "uy"],
            ["id" => 134, "name" => "Venezuela", "code" => "ve"],
            ["id" => 135, "name" => "Vietnam", "code" => "vn"],
            ["id" => 136, "name" => "Washington (US)", "code" => "us_wa"],
            ["id" => 137, "name" => "West Virginia (US)", "code" => "us_wv"],
            ["id" => 138, "name" => "Wisconsin (US)", "code" => "us_wi"],
            ["id" => 139, "name" => "Wyoming (US)", "code" => "us_wy"],
        ];

        DB::table('shuftipro_jurisdiction_codes')->insert($jurisdictions);
    }
}
